/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package SRBanking.ThriftInterface;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AlreadySwarmMemeber extends TException implements org.apache.thrift.TBase<AlreadySwarmMemeber, AlreadySwarmMemeber._Fields>, java.io.Serializable, Cloneable, Comparable<AlreadySwarmMemeber> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AlreadySwarmMemeber");

  private static final org.apache.thrift.protocol.TField RECEIVER_NODE_FIELD_DESC = new org.apache.thrift.protocol.TField("receiverNode", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField LEADER_FIELD_DESC = new org.apache.thrift.protocol.TField("leader", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField TRANSFER_FIELD_DESC = new org.apache.thrift.protocol.TField("transfer", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AlreadySwarmMemeberStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AlreadySwarmMemeberTupleSchemeFactory());
  }

  public NodeID receiverNode; // required
  public NodeID leader; // required
  public TransferID transfer; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RECEIVER_NODE((short)1, "receiverNode"),
    LEADER((short)2, "leader"),
    TRANSFER((short)3, "transfer");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RECEIVER_NODE
          return RECEIVER_NODE;
        case 2: // LEADER
          return LEADER;
        case 3: // TRANSFER
          return TRANSFER;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RECEIVER_NODE, new org.apache.thrift.meta_data.FieldMetaData("receiverNode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, NodeID.class)));
    tmpMap.put(_Fields.LEADER, new org.apache.thrift.meta_data.FieldMetaData("leader", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, NodeID.class)));
    tmpMap.put(_Fields.TRANSFER, new org.apache.thrift.meta_data.FieldMetaData("transfer", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TransferID.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AlreadySwarmMemeber.class, metaDataMap);
  }

  public AlreadySwarmMemeber() {
  }

  public AlreadySwarmMemeber(
    NodeID receiverNode,
    NodeID leader,
    TransferID transfer)
  {
    this();
    this.receiverNode = receiverNode;
    this.leader = leader;
    this.transfer = transfer;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AlreadySwarmMemeber(AlreadySwarmMemeber other) {
    if (other.isSetReceiverNode()) {
      this.receiverNode = new NodeID(other.receiverNode);
    }
    if (other.isSetLeader()) {
      this.leader = new NodeID(other.leader);
    }
    if (other.isSetTransfer()) {
      this.transfer = new TransferID(other.transfer);
    }
  }

  public AlreadySwarmMemeber deepCopy() {
    return new AlreadySwarmMemeber(this);
  }

  @Override
  public void clear() {
    this.receiverNode = null;
    this.leader = null;
    this.transfer = null;
  }

  public NodeID getReceiverNode() {
    return this.receiverNode;
  }

  public AlreadySwarmMemeber setReceiverNode(NodeID receiverNode) {
    this.receiverNode = receiverNode;
    return this;
  }

  public void unsetReceiverNode() {
    this.receiverNode = null;
  }

  /** Returns true if field receiverNode is set (has been assigned a value) and false otherwise */
  public boolean isSetReceiverNode() {
    return this.receiverNode != null;
  }

  public void setReceiverNodeIsSet(boolean value) {
    if (!value) {
      this.receiverNode = null;
    }
  }

  public NodeID getLeader() {
    return this.leader;
  }

  public AlreadySwarmMemeber setLeader(NodeID leader) {
    this.leader = leader;
    return this;
  }

  public void unsetLeader() {
    this.leader = null;
  }

  /** Returns true if field leader is set (has been assigned a value) and false otherwise */
  public boolean isSetLeader() {
    return this.leader != null;
  }

  public void setLeaderIsSet(boolean value) {
    if (!value) {
      this.leader = null;
    }
  }

  public TransferID getTransfer() {
    return this.transfer;
  }

  public AlreadySwarmMemeber setTransfer(TransferID transfer) {
    this.transfer = transfer;
    return this;
  }

  public void unsetTransfer() {
    this.transfer = null;
  }

  /** Returns true if field transfer is set (has been assigned a value) and false otherwise */
  public boolean isSetTransfer() {
    return this.transfer != null;
  }

  public void setTransferIsSet(boolean value) {
    if (!value) {
      this.transfer = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RECEIVER_NODE:
      if (value == null) {
        unsetReceiverNode();
      } else {
        setReceiverNode((NodeID)value);
      }
      break;

    case LEADER:
      if (value == null) {
        unsetLeader();
      } else {
        setLeader((NodeID)value);
      }
      break;

    case TRANSFER:
      if (value == null) {
        unsetTransfer();
      } else {
        setTransfer((TransferID)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RECEIVER_NODE:
      return getReceiverNode();

    case LEADER:
      return getLeader();

    case TRANSFER:
      return getTransfer();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RECEIVER_NODE:
      return isSetReceiverNode();
    case LEADER:
      return isSetLeader();
    case TRANSFER:
      return isSetTransfer();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AlreadySwarmMemeber)
      return this.equals((AlreadySwarmMemeber)that);
    return false;
  }

  public boolean equals(AlreadySwarmMemeber that) {
    if (that == null)
      return false;

    boolean this_present_receiverNode = true && this.isSetReceiverNode();
    boolean that_present_receiverNode = true && that.isSetReceiverNode();
    if (this_present_receiverNode || that_present_receiverNode) {
      if (!(this_present_receiverNode && that_present_receiverNode))
        return false;
      if (!this.receiverNode.equals(that.receiverNode))
        return false;
    }

    boolean this_present_leader = true && this.isSetLeader();
    boolean that_present_leader = true && that.isSetLeader();
    if (this_present_leader || that_present_leader) {
      if (!(this_present_leader && that_present_leader))
        return false;
      if (!this.leader.equals(that.leader))
        return false;
    }

    boolean this_present_transfer = true && this.isSetTransfer();
    boolean that_present_transfer = true && that.isSetTransfer();
    if (this_present_transfer || that_present_transfer) {
      if (!(this_present_transfer && that_present_transfer))
        return false;
      if (!this.transfer.equals(that.transfer))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(AlreadySwarmMemeber other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetReceiverNode()).compareTo(other.isSetReceiverNode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReceiverNode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.receiverNode, other.receiverNode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLeader()).compareTo(other.isSetLeader());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLeader()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.leader, other.leader);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTransfer()).compareTo(other.isSetTransfer());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTransfer()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.transfer, other.transfer);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AlreadySwarmMemeber(");
    boolean first = true;

    sb.append("receiverNode:");
    if (this.receiverNode == null) {
      sb.append("null");
    } else {
      sb.append(this.receiverNode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("leader:");
    if (this.leader == null) {
      sb.append("null");
    } else {
      sb.append(this.leader);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("transfer:");
    if (this.transfer == null) {
      sb.append("null");
    } else {
      sb.append(this.transfer);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (receiverNode != null) {
      receiverNode.validate();
    }
    if (leader != null) {
      leader.validate();
    }
    if (transfer != null) {
      transfer.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AlreadySwarmMemeberStandardSchemeFactory implements SchemeFactory {
    public AlreadySwarmMemeberStandardScheme getScheme() {
      return new AlreadySwarmMemeberStandardScheme();
    }
  }

  private static class AlreadySwarmMemeberStandardScheme extends StandardScheme<AlreadySwarmMemeber> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AlreadySwarmMemeber struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RECEIVER_NODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.receiverNode = new NodeID();
              struct.receiverNode.read(iprot);
              struct.setReceiverNodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LEADER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.leader = new NodeID();
              struct.leader.read(iprot);
              struct.setLeaderIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TRANSFER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.transfer = new TransferID();
              struct.transfer.read(iprot);
              struct.setTransferIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AlreadySwarmMemeber struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.receiverNode != null) {
        oprot.writeFieldBegin(RECEIVER_NODE_FIELD_DESC);
        struct.receiverNode.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.leader != null) {
        oprot.writeFieldBegin(LEADER_FIELD_DESC);
        struct.leader.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.transfer != null) {
        oprot.writeFieldBegin(TRANSFER_FIELD_DESC);
        struct.transfer.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AlreadySwarmMemeberTupleSchemeFactory implements SchemeFactory {
    public AlreadySwarmMemeberTupleScheme getScheme() {
      return new AlreadySwarmMemeberTupleScheme();
    }
  }

  private static class AlreadySwarmMemeberTupleScheme extends TupleScheme<AlreadySwarmMemeber> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AlreadySwarmMemeber struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetReceiverNode()) {
        optionals.set(0);
      }
      if (struct.isSetLeader()) {
        optionals.set(1);
      }
      if (struct.isSetTransfer()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetReceiverNode()) {
        struct.receiverNode.write(oprot);
      }
      if (struct.isSetLeader()) {
        struct.leader.write(oprot);
      }
      if (struct.isSetTransfer()) {
        struct.transfer.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AlreadySwarmMemeber struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.receiverNode = new NodeID();
        struct.receiverNode.read(iprot);
        struct.setReceiverNodeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.leader = new NodeID();
        struct.leader.read(iprot);
        struct.setLeaderIsSet(true);
      }
      if (incoming.get(2)) {
        struct.transfer = new TransferID();
        struct.transfer.read(iprot);
        struct.setTransferIsSet(true);
      }
    }
  }

}

