/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package SRBanking.ThriftInterface;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class NotEnoughMembersToMakeTransfer extends TException implements org.apache.thrift.TBase<NotEnoughMembersToMakeTransfer, NotEnoughMembersToMakeTransfer._Fields>, java.io.Serializable, Cloneable, Comparable<NotEnoughMembersToMakeTransfer> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("NotEnoughMembersToMakeTransfer");

  private static final org.apache.thrift.protocol.TField MEMBERS_AVAILABLE_FIELD_DESC = new org.apache.thrift.protocol.TField("membersAvailable", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField MEMBERS_REQUESTED_FIELD_DESC = new org.apache.thrift.protocol.TField("membersRequested", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new NotEnoughMembersToMakeTransferStandardSchemeFactory());
    schemes.put(TupleScheme.class, new NotEnoughMembersToMakeTransferTupleSchemeFactory());
  }

  public long membersAvailable; // required
  public long membersRequested; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MEMBERS_AVAILABLE((short)1, "membersAvailable"),
    MEMBERS_REQUESTED((short)2, "membersRequested");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MEMBERS_AVAILABLE
          return MEMBERS_AVAILABLE;
        case 2: // MEMBERS_REQUESTED
          return MEMBERS_REQUESTED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MEMBERSAVAILABLE_ISSET_ID = 0;
  private static final int __MEMBERSREQUESTED_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MEMBERS_AVAILABLE, new org.apache.thrift.meta_data.FieldMetaData("membersAvailable", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.MEMBERS_REQUESTED, new org.apache.thrift.meta_data.FieldMetaData("membersRequested", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(NotEnoughMembersToMakeTransfer.class, metaDataMap);
  }

  public NotEnoughMembersToMakeTransfer() {
  }

  public NotEnoughMembersToMakeTransfer(
    long membersAvailable,
    long membersRequested)
  {
    this();
    this.membersAvailable = membersAvailable;
    setMembersAvailableIsSet(true);
    this.membersRequested = membersRequested;
    setMembersRequestedIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NotEnoughMembersToMakeTransfer(NotEnoughMembersToMakeTransfer other) {
    __isset_bitfield = other.__isset_bitfield;
    this.membersAvailable = other.membersAvailable;
    this.membersRequested = other.membersRequested;
  }

  public NotEnoughMembersToMakeTransfer deepCopy() {
    return new NotEnoughMembersToMakeTransfer(this);
  }

  @Override
  public void clear() {
    setMembersAvailableIsSet(false);
    this.membersAvailable = 0;
    setMembersRequestedIsSet(false);
    this.membersRequested = 0;
  }

  public long getMembersAvailable() {
    return this.membersAvailable;
  }

  public NotEnoughMembersToMakeTransfer setMembersAvailable(long membersAvailable) {
    this.membersAvailable = membersAvailable;
    setMembersAvailableIsSet(true);
    return this;
  }

  public void unsetMembersAvailable() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MEMBERSAVAILABLE_ISSET_ID);
  }

  /** Returns true if field membersAvailable is set (has been assigned a value) and false otherwise */
  public boolean isSetMembersAvailable() {
    return EncodingUtils.testBit(__isset_bitfield, __MEMBERSAVAILABLE_ISSET_ID);
  }

  public void setMembersAvailableIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MEMBERSAVAILABLE_ISSET_ID, value);
  }

  public long getMembersRequested() {
    return this.membersRequested;
  }

  public NotEnoughMembersToMakeTransfer setMembersRequested(long membersRequested) {
    this.membersRequested = membersRequested;
    setMembersRequestedIsSet(true);
    return this;
  }

  public void unsetMembersRequested() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MEMBERSREQUESTED_ISSET_ID);
  }

  /** Returns true if field membersRequested is set (has been assigned a value) and false otherwise */
  public boolean isSetMembersRequested() {
    return EncodingUtils.testBit(__isset_bitfield, __MEMBERSREQUESTED_ISSET_ID);
  }

  public void setMembersRequestedIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MEMBERSREQUESTED_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MEMBERS_AVAILABLE:
      if (value == null) {
        unsetMembersAvailable();
      } else {
        setMembersAvailable((Long)value);
      }
      break;

    case MEMBERS_REQUESTED:
      if (value == null) {
        unsetMembersRequested();
      } else {
        setMembersRequested((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MEMBERS_AVAILABLE:
      return Long.valueOf(getMembersAvailable());

    case MEMBERS_REQUESTED:
      return Long.valueOf(getMembersRequested());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MEMBERS_AVAILABLE:
      return isSetMembersAvailable();
    case MEMBERS_REQUESTED:
      return isSetMembersRequested();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof NotEnoughMembersToMakeTransfer)
      return this.equals((NotEnoughMembersToMakeTransfer)that);
    return false;
  }

  public boolean equals(NotEnoughMembersToMakeTransfer that) {
    if (that == null)
      return false;

    boolean this_present_membersAvailable = true;
    boolean that_present_membersAvailable = true;
    if (this_present_membersAvailable || that_present_membersAvailable) {
      if (!(this_present_membersAvailable && that_present_membersAvailable))
        return false;
      if (this.membersAvailable != that.membersAvailable)
        return false;
    }

    boolean this_present_membersRequested = true;
    boolean that_present_membersRequested = true;
    if (this_present_membersRequested || that_present_membersRequested) {
      if (!(this_present_membersRequested && that_present_membersRequested))
        return false;
      if (this.membersRequested != that.membersRequested)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(NotEnoughMembersToMakeTransfer other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMembersAvailable()).compareTo(other.isSetMembersAvailable());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMembersAvailable()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.membersAvailable, other.membersAvailable);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMembersRequested()).compareTo(other.isSetMembersRequested());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMembersRequested()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.membersRequested, other.membersRequested);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("NotEnoughMembersToMakeTransfer(");
    boolean first = true;

    sb.append("membersAvailable:");
    sb.append(this.membersAvailable);
    first = false;
    if (!first) sb.append(", ");
    sb.append("membersRequested:");
    sb.append(this.membersRequested);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class NotEnoughMembersToMakeTransferStandardSchemeFactory implements SchemeFactory {
    public NotEnoughMembersToMakeTransferStandardScheme getScheme() {
      return new NotEnoughMembersToMakeTransferStandardScheme();
    }
  }

  private static class NotEnoughMembersToMakeTransferStandardScheme extends StandardScheme<NotEnoughMembersToMakeTransfer> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, NotEnoughMembersToMakeTransfer struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MEMBERS_AVAILABLE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.membersAvailable = iprot.readI64();
              struct.setMembersAvailableIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MEMBERS_REQUESTED
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.membersRequested = iprot.readI64();
              struct.setMembersRequestedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, NotEnoughMembersToMakeTransfer struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(MEMBERS_AVAILABLE_FIELD_DESC);
      oprot.writeI64(struct.membersAvailable);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MEMBERS_REQUESTED_FIELD_DESC);
      oprot.writeI64(struct.membersRequested);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class NotEnoughMembersToMakeTransferTupleSchemeFactory implements SchemeFactory {
    public NotEnoughMembersToMakeTransferTupleScheme getScheme() {
      return new NotEnoughMembersToMakeTransferTupleScheme();
    }
  }

  private static class NotEnoughMembersToMakeTransferTupleScheme extends TupleScheme<NotEnoughMembersToMakeTransfer> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, NotEnoughMembersToMakeTransfer struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMembersAvailable()) {
        optionals.set(0);
      }
      if (struct.isSetMembersRequested()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMembersAvailable()) {
        oprot.writeI64(struct.membersAvailable);
      }
      if (struct.isSetMembersRequested()) {
        oprot.writeI64(struct.membersRequested);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, NotEnoughMembersToMakeTransfer struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.membersAvailable = iprot.readI64();
        struct.setMembersAvailableIsSet(true);
      }
      if (incoming.get(1)) {
        struct.membersRequested = iprot.readI64();
        struct.setMembersRequestedIsSet(true);
      }
    }
  }

}

