/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace SRBanking.ThriftInterface
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Swarm : TBase
  {
    private NodeID _Leader;
    private List<NodeID> _Members;
    private TransferID _Transfer;

    public NodeID Leader
    {
      get
      {
        return _Leader;
      }
      set
      {
        __isset.Leader = true;
        this._Leader = value;
      }
    }

    public List<NodeID> Members
    {
      get
      {
        return _Members;
      }
      set
      {
        __isset.Members = true;
        this._Members = value;
      }
    }

    public TransferID Transfer
    {
      get
      {
        return _Transfer;
      }
      set
      {
        __isset.Transfer = true;
        this._Transfer = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Leader;
      public bool Members;
      public bool Transfer;
    }

    public Swarm() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Leader = new NodeID();
              Leader.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                Members = new List<NodeID>();
                TList _list4 = iprot.ReadListBegin();
                for( int _i5 = 0; _i5 < _list4.Count; ++_i5)
                {
                  NodeID _elem6 = new NodeID();
                  _elem6 = new NodeID();
                  _elem6.Read(iprot);
                  Members.Add(_elem6);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              Transfer = new TransferID();
              Transfer.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Swarm");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Leader != null && __isset.Leader) {
        field.Name = "Leader";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        Leader.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Members != null && __isset.Members) {
        field.Name = "Members";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Members.Count));
          foreach (NodeID _iter7 in Members)
          {
            _iter7.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (Transfer != null && __isset.Transfer) {
        field.Name = "Transfer";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        Transfer.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Swarm(");
      sb.Append("Leader: ");
      sb.Append(Leader== null ? "<null>" : Leader.ToString());
      sb.Append(",Members: ");
      sb.Append(Members);
      sb.Append(",Transfer: ");
      sb.Append(Transfer== null ? "<null>" : Transfer.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
