/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace SRBanking.ThriftInterface
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class NodeID : TBase
  {
    private IPAddress _Address;
    private int _Port;

    public IPAddress Address
    {
      get
      {
        return _Address;
      }
      set
      {
        __isset.Address = true;
        this._Address = value;
      }
    }

    public int Port
    {
      get
      {
        return _Port;
      }
      set
      {
        __isset.Port = true;
        this._Port = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Address;
      public bool Port;
    }

    public NodeID() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Address = new IPAddress();
              Address.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              Port = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("NodeID");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Address != null && __isset.Address) {
        field.Name = "Address";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        Address.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (__isset.Port) {
        field.Name = "Port";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Port);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("NodeID(");
      sb.Append("Address: ");
      sb.Append(Address== null ? "<null>" : Address.ToString());
      sb.Append(",Port: ");
      sb.Append(Port);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
