/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace SRBanking.ThriftInterface
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class NotEnoughMoney : TException, TBase
  {
    private long _moneyAvailable;
    private long _moneyRequested;

    public long MoneyAvailable
    {
      get
      {
        return _moneyAvailable;
      }
      set
      {
        __isset.moneyAvailable = true;
        this._moneyAvailable = value;
      }
    }

    public long MoneyRequested
    {
      get
      {
        return _moneyRequested;
      }
      set
      {
        __isset.moneyRequested = true;
        this._moneyRequested = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool moneyAvailable;
      public bool moneyRequested;
    }

    public NotEnoughMoney() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              MoneyAvailable = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              MoneyRequested = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("NotEnoughMoney");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.moneyAvailable) {
        field.Name = "moneyAvailable";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(MoneyAvailable);
        oprot.WriteFieldEnd();
      }
      if (__isset.moneyRequested) {
        field.Name = "moneyRequested";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(MoneyRequested);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("NotEnoughMoney(");
      sb.Append("MoneyAvailable: ");
      sb.Append(MoneyAvailable);
      sb.Append(",MoneyRequested: ");
      sb.Append(MoneyRequested);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
