/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace SRBanking.ThriftInterface
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class NotEnoughMembersToMakeTransfer : TException, TBase
  {
    private long _membersAvailable;
    private long _membersRequested;

    public long MembersAvailable
    {
      get
      {
        return _membersAvailable;
      }
      set
      {
        __isset.membersAvailable = true;
        this._membersAvailable = value;
      }
    }

    public long MembersRequested
    {
      get
      {
        return _membersRequested;
      }
      set
      {
        __isset.membersRequested = true;
        this._membersRequested = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool membersAvailable;
      public bool membersRequested;
    }

    public NotEnoughMembersToMakeTransfer() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              MembersAvailable = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              MembersRequested = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("NotEnoughMembersToMakeTransfer");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.membersAvailable) {
        field.Name = "membersAvailable";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(MembersAvailable);
        oprot.WriteFieldEnd();
      }
      if (__isset.membersRequested) {
        field.Name = "membersRequested";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(MembersRequested);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("NotEnoughMembersToMakeTransfer(");
      sb.Append("MembersAvailable: ");
      sb.Append(MembersAvailable);
      sb.Append(",MembersRequested: ");
      sb.Append(MembersRequested);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
