/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace SRBanking.ThriftInterface
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TransferData : TBase
  {
    private TransferID _transferID;
    private NodeID _receiver;
    private long _value;

    public TransferID TransferID
    {
      get
      {
        return _transferID;
      }
      set
      {
        __isset.transferID = true;
        this._transferID = value;
      }
    }

    public NodeID Receiver
    {
      get
      {
        return _receiver;
      }
      set
      {
        __isset.receiver = true;
        this._receiver = value;
      }
    }

    public long Value
    {
      get
      {
        return _value;
      }
      set
      {
        __isset.value = true;
        this._value = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool transferID;
      public bool receiver;
      public bool value;
    }

    public TransferData() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              TransferID = new TransferID();
              TransferID.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              Receiver = new NodeID();
              Receiver.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I64) {
              Value = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TransferData");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (TransferID != null && __isset.transferID) {
        field.Name = "transferID";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        TransferID.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Receiver != null && __isset.receiver) {
        field.Name = "receiver";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        Receiver.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (__isset.value) {
        field.Name = "value";
        field.Type = TType.I64;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Value);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TransferData(");
      sb.Append("TransferID: ");
      sb.Append(TransferID== null ? "<null>" : TransferID.ToString());
      sb.Append(",Receiver: ");
      sb.Append(Receiver== null ? "<null>" : Receiver.ToString());
      sb.Append(",Value: ");
      sb.Append(Value);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
